stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: "diwkakrutywka/diana_lab"
  DOCKER_DRIVER: "overlay2"

test:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$diwkakrutywka" -p "$Kgmsad45"
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$diwkakrutywka" -p "$Kgmsad45"
  script:
    - docker stop flask-app || true
    - docker rm flask-app || true
    - docker run -d -p 5000:5000 --name flask-app $IMAGE_NAME:latest
