stages:
  - test
  - build
  - deploy

variables:
  IMAGE_NAME: "diwkakrutywka/diana_lab"
  DOCKER_DRIVER: "overlay2"

test:
  stage: test
  image: python:3.9
  before_script:
    - pip install -r requirements.txt || pip install pytest
  script:
    - pytest

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  script:
    - docker stop flask-app || true
    - docker rm flask-app || true
    - docker pull $IMAGE_NAME:latest
    - docker run -d -p 5000:5000 --name flask-app --restart=always $IMAGE_NAME:latest
