name: CI Pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      

  notify:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.EMAIL_HOST }} 
          server_port: 587 
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "CI/CD Pipeline Notification"
          body: "Your pipeline has completed successfully!"
          to: "your-email@example.com"
          from: "CI Bot <ci-notifications@example.com>"
          secure: false 
