name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v3

      - name: Логин в Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Сборка и пуш образа
        run: |
          docker build -t my-dockerhub-user/my-app:latest .
          docker tag my-dockerhub-user/my-app:latest my-dockerhub-user/my-app:${{ github.sha }}
          docker push my-dockerhub-user/my-app:latest
          docker push my-dockerhub-user/my-app:${{ github.sha }}

      - name: Развертывание на сервере
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull my-dockerhub-user/my-app:latest
            docker stop my-app || true
            docker rm my-app || true
            docker run -d -p 8080:80 --name my-app my-dockerhub-user/my-app:latest
